### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by WyattParker** [terreng/computercraft-streaming-music#4]
Trying to self host
You don't mention anything about overwriting package.json, so are we supposed to?

Trying to self host for fun and to learn how to use Firebase, and running into "Error" when attempting to use URL or search, so trying to make sure I'm not missing something.

**Comment by terreng** [comment]
I can't tell what you're asking

**Comment by WyattParker** [comment]
So when it asks us to overwrite functions/package.json, we say "no" correct?

**Comment by terreng** [comment]
> If I say no, then nothing works at all, nothing deploys, etc.

This doesn't give me much information. Why doesn't it deploy? What's the error?

Pretend you're me. I haven't touched the code for this project in a couple months so I'm a little rusty. It would help if you provided the exact steps that you took, and the exact place where something went wrong / an error occurred. Otherwise I'm trying to piece together what you mean.

If you want me to help you, please make it exceptionally easy for me to help you.

From what you've said, it sounds like you might not be running `npm install` inside of the `functions` directory as the instructions say you should. You are correct for picking "no" when the firebase command asks about overwriting.

**Comment by WyattParker** [comment]
No problem, I'm sorry if I seem vague, i swear I'm not trying to be and not trying to be a problem or annoying.
Upon saying "no" to overwriting package.json and index.js,then yes to installing dependencies, npm returns errors.

`? What language would you like to use to write Cloud Functions? JavaScript
? Do you want to use ESLint to catch probable bugs and enforce style? No
? File functions/package.json already exists. Overwrite? No
i  Skipping write of functions/package.json
? File functions/index.js already exists. Overwrite? No
i  Skipping write of functions/index.js
+  Wrote functions/.gitignore
? Do you want to install dependencies with npm now? Yes
npm error code ENOENT
npm error syscall spawn git
npm error path git
npm error errno -4058
npm error enoent An unknown git error occurred
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-10-01T01_55_24_650Z-debug-0.log

NPM install failed, continuing with Firebase initialization...

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...
i  Writing gitignore file to .gitignore...

+  Firebase initialization complete!
PS C:\mcmusic> cd functions
PS C:\mcmusic\functions> npm install
npm error code ENOENT
npm error syscall spawn git
npm error path git
npm error errno -4058
npm error enoent An unknown git error occurred
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-10-01T01_57_49_984Z-debug-0.log
PS C:\mcmusic\functions>`
even manually trying to run `npm install firebase-functions` or any other dependency just fails.
Sorry if I'm annoying, I'm just doing this for fun and trying to fully learn/understand

**Comment by terreng** [comment]
No problem, it's just that most people on GitHub and forums like Stack Overflow don't have a lot of patience. So if you want help, it's better to be very specific about what you've tried, where you're getting stuck, etc.

As soon as you get to a step that doesn't work, you should assume that's the source of the problem if the steps after don't work either. So in this case, you ran in to an error with npm. That's the thing you should try to solve first, and that's the most relevant thing to mention. 

Looking at your error, it says:

npm error enoent An unknown git error occurred
npm error enoent This is related to npm not being able to find a file.

This tells me that there's a problem with git. It might not be installed correctly. 

So the first thing you can try is running `git --version` to see if it works. If not, try reinstalling git, making sure it's in your PATH variable, etc. I can't help you with any of that, but there are guides out there that can. 

You can also try asking Claude or ChatGPT for help with errors. Take it with a grain of salt, but sometimes it can push you in the right direction.

I'm going to close this issue for now since the problem you're having is with npm / git, and not my code. But feel free to leave another comment even though the issue is closed.

**Comment by WyattParker** [comment]
Reinstalled Git and it built perfectly and pushed to Firebase with no problem.
However, upon searching/pasting a YouTube link, still returns "Error" in Minecraft

**Comment by terreng** [comment]
Glad to hear it!
